# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSecilenleriAl = QtWidgets.QPushButton(self.centralwidget)
        self.btnSecilenleriAl.setGeometry(QtCore.QRect(80, 340, 261, 51))
        self.btnSecilenleriAl.setObjectName("btnSecilenleriAl")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(360, 340, 241, 121))
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        self.groupHobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobiler.setGeometry(QtCore.QRect(80, 30, 261, 291))
        self.groupHobiler.setObjectName("groupHobiler")
        self.layoutWidget = QtWidgets.QWidget(self.groupHobiler)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 241, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSinema = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbSinema.setObjectName("cbSinema")
        self.verticalLayout.addWidget(self.cbSinema)
        self.cbKitap = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbKitap.setObjectName("cbKitap")
        self.verticalLayout.addWidget(self.cbKitap)
        self.cbSpor = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbSpor.setObjectName("cbSpor")
        self.verticalLayout.addWidget(self.cbSpor)
        self.groupHobiler_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobiler_2.setGeometry(QtCore.QRect(390, 30, 261, 291))
        self.groupHobiler_2.setObjectName("groupHobiler_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupHobiler_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 40, 241, 191))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbSinema_4 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.cbSinema_4.setObjectName("cbSinema_4")
        self.verticalLayout_4.addWidget(self.cbSinema_4)
        self.cbKitap_4 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.cbKitap_4.setObjectName("cbKitap_4")
        self.verticalLayout_4.addWidget(self.cbKitap_4)
        self.cbSpor_4 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.cbSpor_4.setObjectName("cbSpor_4")
        self.verticalLayout_4.addWidget(self.cbSpor_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSecilenleriAl.setText(_translate("MainWindow", "Secimleri Al"))
        self.groupHobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbSinema.setText(_translate("MainWindow", "Sinema"))
        self.cbKitap.setText(_translate("MainWindow", "Kitap Okuma"))
        self.cbSpor.setText(_translate("MainWindow", "Spor"))
        self.groupHobiler_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbSinema_4.setText(_translate("MainWindow", "Sinema"))
        self.cbKitap_4.setText(_translate("MainWindow", "Kitap Okuma"))
        self.cbSpor_4.setText(_translate("MainWindow", "Spor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
